### PR TITLE
Implement card rippling

### PR DESCRIPTION
**Pull request by mzgajner**
Fixes [this bug](https://trello.com/c/MkR6kjVW/165-da-se-odpravi-bug-v-headerju-seznamov).

I went through [this jQuery function](https://github.com/danesjenovdan/parlassets/blob/master/js/script.js#L324-L431) and replaced it with Vue functionality. As far as I checked, all the functionality should be replaced pretty much identically and the issue linked above is solved. Also, I can sleep better at night, knowing something inside Vue's scope isn't getting poked by jQuery on the side.

I need an opinion though. If you check out the template for `p/seznam-poslancev` below, you can see that I had to make a few changes which will basically have to be replicated in all (Vue-based) card templates. I see two ways of doing this:
1. Just Do It everywhere OR
2. Make a `CardContainer` component which uses header, footer, embed, share and info and provides a few slots/props for customization. Use this component in all cards.

At this point, both of these are about the same amount of work as all cards need to be updated anyway. The second one will make updates similar to this one a bit easier in the future, so I generally prefer it, but it will add a component and a bit of abstraction. What are your feelings on this?

### CODE REVIEW

**Comment by muki** [comment]
I'd prefer the component as well at this point, but I have a question.

If I understand correctly, you implemented this on p/seznam-poslancev where you already generated your infoText dynamically. If we move this to all other cards, we'd have to supply the infoText dynamically through a prop as well. Amirite? Are there any other extra props you'd consider adding to this component?

Otherwise this looks good to me. The only thing left to consider are SCSS styles. Currently, most of the styles for card components live in [Parlassets](https://github.com/danesjenovdan/parlassets/blob/master/scss/_card.scss). Should this be moved to Vue components as well?

**Comment by mzgajner** [comment]
Yes, the info text is dynamic, but the `CardInfo` component actually has [a slot](https://github.com/danesjenovdan/parlanode/blob/3a1758dfc8c1d9ecf566da365e0aba71d65a6316/cards/p/seznam-poslancev/InnerCard.vue#L7), not a property. I wouldn't change that, I'd just have a named slot for this on the new component and pass it through, since it can work easily with both dynamic and static infot exts.

As far as styles go, I absolutely agree with you, but I'd wait with this until all cards are ported to Vue. It will be trivial to simply move it into particular components then.

**Comment by muki** [comment]
OK. Let's leave the styles as they are right now. Will you then create the abstract component? I think I have an idea how to go about it, but I'd trust you more with it. If not, I'll give it a go and send it your way for a review.

Once the abstract component is done I guess this will be ready for merge. :)

**Comment by mzgajner** [comment]
Nope, I got it, just wanted your opinion. Will poke you when it's done (ETA tomorrow after work).

**Comment by muki** [comment]
I added callback functionality to `Footer.vue` and commited an example where I need it. If we can take care of a situation like this in some other fashion let me know. :)

@mzgajner I didn't pull-request your pull-request so you can pull-request while you pull-request. Please just check bf90028 and decide if it makes sense.

**Comment by mzgajner** [comment]
@muki finished extraction to wrapper component, see commit. I tried opening and clicking all converted cards, they worked and didn't throw any errors apart from one obcasnik card that didn't work even before it was changed.

As far as your changes go, I didn't agree with them for two reasons:
1. There was already an update being performed right in the middle of the ripple - `currentBack` was being updated (see it [here](https://github.com/danesjenovdan/parlanode/pull/2/files#diff-774dad13dc4ec74fd612cb3fb302a738R39) in your PR as this one changed). Instead of setting up another timeout, I'd prefer to rely on that change, set up a watcher and go from there. Since your chart update relied on the element being present, [`nextTick`](https://vuejs.org/v2/api/#vm-nextTick) would probably come in handy.
2. Passing callbacks is not the best pattern (I know, I encouraged it in the past :blush:) - the recommended way to go about it is to trigger an event from the child. Check out the last commit to see it in action.

As far as I'm concerned, this PR is finished.

**Pull request merged**
